package HowToPlay;

import Home.Home;
import Exit.Exit;
import Home.Open;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class HowToPlay extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlay
     */
    public static HowToPlay frame = new HowToPlay();
    private final Exit exit = new Exit();
    private static URL[] photos;
    private static int i;
    
    
    public HowToPlay() {
        i = 0;
        HowToPlay.photos = new URL[]{getClass().getResource("/HowToPlay/1.png"), getClass().getResource("/HowToPlay/2.png"), getClass().getResource("/HowToPlay/3.png"), getClass().getResource("/HowToPlay/4.png"), getClass().getResource("/HowToPlay/5.png"), getClass().getResource("/HowToPlay/6.png"), getClass().getResource("/HowToPlay/7.png"), getClass().getResource("/HowToPlay/8.png"), getClass().getResource("/HowToPlay/9.png"), getClass().getResource("/HowToPlay/10.png"), getClass().getResource("/HowToPlay/11.png"), getClass().getResource("/HowToPlay/12.png"), getClass().getResource("/HowToPlay/13.png"), getClass().getResource("/HowToPlay/14.png"), getClass().getResource("/HowToPlay/15.png"), getClass().getResource("/HowToPlay/16.png"), getClass().getResource("/HowToPlay/17.png"), getClass().getResource("/HowToPlay/18.png"), getClass().getResource("/HowToPlay/19.png"), getClass().getResource("/HowToPlay/20.png"), getClass().getResource("/HowToPlay/21.png"), getClass().getResource("/HowToPlay/22.png"), getClass().getResource("/HowToPlay/23.png"), getClass().getResource("/HowToPlay/24.png"), getClass().getResource("/HowToPlay/25.png"), getClass().getResource("/HowToPlay/26.png"), getClass().getResource("/HowToPlay/27.png"), getClass().getResource("/HowToPlay/28.png"), getClass().getResource("/HowToPlay/29.png"), getClass().getResource("/HowToPlay/30.png"), getClass().getResource("/HowToPlay/31.png"), getClass().getResource("/HowToPlay/32.png"), getClass().getResource("/HowToPlay/33.png"), getClass().getResource("/HowToPlay/34.png"), getClass().getResource("/HowToPlay/35.png"), getClass().getResource("/HowToPlay/36.png"), getClass().getResource("/HowToPlay/38.png"), getClass().getResource("/HowToPlay/39.png"), getClass().getResource("/HowToPlay/40.png"), getClass().getResource("/HowToPlay/41.png"), getClass().getResource("/HowToPlay/42.png"), getClass().getResource("/HowToPlay/43.png"), getClass().getResource("/HowToPlay/44.png"), getClass().getResource("/HowToPlay/45.png"), getClass().getResource("/HowToPlay/46.png"), getClass().getResource("/HowToPlay/47.png"), getClass().getResource("/HowToPlay/48.png"), getClass().getResource("/HowToPlay/49.png"), getClass().getResource("/HowToPlay/50.png"), getClass().getResource("/HowToPlay/51.png"), getClass().getResource("/HowToPlay/52.png"), getClass().getResource("/HowToPlay/53.png"), getClass().getResource("/HowToPlay/54.png"), getClass().getResource("/HowToPlay/55.png"), getClass().getResource("/HowToPlay/56.png"), getClass().getResource("/HowToPlay/57.png"), getClass().getResource("/HowToPlay/58.png"), getClass().getResource("/HowToPlay/59.png"), getClass().getResource("/HowToPlay/60.png")};
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        sound = new javax.swing.JButton();
        gotIt = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit/exit.png"))); // NOI18N
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setFocusPainted(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(0, 0, 200, 70);

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sound/on.png"))); // NOI18N
        sound.setBorderPainted(false);
        sound.setContentAreaFilled(false);
        sound.setFocusPainted(false);
        sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundActionPerformed(evt);
            }
        });
        getContentPane().add(sound);
        sound.setBounds(1240, 0, 122, 128);

        gotIt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HowToPlay/got-it.png"))); // NOI18N
        gotIt.setBorderPainted(false);
        gotIt.setContentAreaFilled(false);
        gotIt.setDefaultCapable(false);
        gotIt.setFocusPainted(false);
        gotIt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gotItMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gotItMouseExited(evt);
            }
        });
        gotIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotItActionPerformed(evt);
            }
        });
        getContentPane().add(gotIt);
        gotIt.setBounds(600, 680, 210, 78);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HowToPlay/1.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/exit-clicked.png"));
        exitButton.setIcon(image);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/exit.png"));
        exitButton.setIcon(image);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        exit.setTitle("Memory Game");
        exit.setSize(600, 446);
        exit.setVisible(true);
        exit.setLocationRelativeTo(null);
        exit.setResizable(false);
        this.setEnabled(false);
        Exit.from = "HowToPlay";
    }//GEN-LAST:event_exitButtonActionPerformed

    public static void setIt(){
        frame.setEnabled(true);
    }
    
    private void soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(!Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute.png"));
            sound.setIcon(image);
            Home.audioClip.stop();
            Home.mute = true;
        }
        else{
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/on.png"));
            sound.setIcon(image);
            Home.audioClip.loop(Clip.LOOP_CONTINUOUSLY);
            Home.audioClip.start();
            Home.mute = false;
        }
    }//GEN-LAST:event_soundActionPerformed

    private void gotItMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotItMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/HowToPlay/got-it-clicked.png"));
        gotIt.setIcon(image);
    }//GEN-LAST:event_gotItMouseEntered

    private void gotItMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotItMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/HowToPlay/got-it.png"));
        gotIt.setIcon(image);
    }//GEN-LAST:event_gotItMouseExited

    private void gotItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotItActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute.png"));
            Home.sound.setIcon(image);
        }
        frame.setVisible(false);
        frame = null;
        Home.frame.setVisible(true);
        Open.t1.stop();
    }//GEN-LAST:event_gotItActionPerformed

    private static void time(double time){
        double end = System.currentTimeMillis() + time;
        while(System.currentTimeMillis() < end){
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frame.setTitle("Memory Game");
                frame.setSize(1366, 768);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                frame.setVisible(true);
                if(Home.mute){
                    ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute(1).png"));
                    sound.setIcon(image);
                }
            }
        });
        time(500);
        while(true){
            if(i == 59)
                i = 0;
            time(150);
            background.setIcon(new ImageIcon(photos[i]));
            i++;
        }       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel background;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gotIt;
    private static javax.swing.JButton sound;
    // End of variables declaration//GEN-END:variables
}
