package Home;

import AboutTheGame.AboutTheGame;
import Exit.Exit;
import HighScore.HighScore;
import Play.Play;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

/**
 *
 * @author Ahmed
 */
public class Home extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Main
     */
    public static Home frame = null;
    private final Exit exit = new Exit();
    public static AudioInputStream audioStream;
    public static AudioFormat format;
    public static DataLine.Info info = new DataLine.Info(Clip.class, format);
    public static Clip audioClip;
    public static AudioInputStream audioStream1;
    public static AudioFormat format1;
    public static DataLine.Info info1 = new DataLine.Info(Clip.class, format1);
    public static Clip audioClip1;
    public static AudioInputStream audioStream2;
    public static AudioFormat format2;
    public static DataLine.Info info2 = new DataLine.Info(Clip.class, format2);
    public static Clip audioClip2;
    public static AudioInputStream audioStream3;
    public static AudioFormat format3;
    public static DataLine.Info info3 = new DataLine.Info(Clip.class, format3);
    public static Clip audioClip3;
    public static AudioInputStream audioStream4;
    public static AudioFormat format4;
    public static DataLine.Info info4 = new DataLine.Info(Clip.class, format4);
    public static Clip audioClip4;
    public static boolean mute = false;
    boolean y;
    public static File scoreEasy = new File("Scores//EasyLevel.txt");
    public static File scoreMedium = new File("Scores//MediumLevel.txt");
    public static File scoreHard = new File("Scores//HardLevel.txt");
    
    public Home() throws FileNotFoundException, IOException, LineUnavailableException, UnsupportedAudioFileException{
        audioStream = AudioSystem.getAudioInputStream(new File("Audio//background.wav"));
        format = audioStream.getFormat();
        audioClip = (Clip) AudioSystem.getLine(info);
        audioClip.open(audioStream);
        audioClip.loop(Clip.LOOP_CONTINUOUSLY);
        audioClip.start();
        audioStream1 = AudioSystem.getAudioInputStream(new File("Audio//click.wav"));
        format1 = audioStream1.getFormat();
        audioClip1 = (Clip) AudioSystem.getLine(info1);
        audioClip1.open(audioStream1);
        audioStream2 = AudioSystem.getAudioInputStream(new File("Audio//win.wav"));
        format2 = audioStream2.getFormat();
        audioClip2 = (Clip) AudioSystem.getLine(info2);
        audioClip2.open(audioStream2);
        audioStream3 = AudioSystem.getAudioInputStream(new File("Audio//correct.wav"));
        format3 = audioStream3.getFormat();
        audioClip3 = (Clip) AudioSystem.getLine(info3);
        audioClip3.open(audioStream3);
        audioStream4 = AudioSystem.getAudioInputStream(new File("Audio//Losing.wav"));
        format4 = audioStream4.getFormat();
        audioClip4 = (Clip) AudioSystem.getLine(info4);
        audioClip4.open(audioStream4);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        sound = new javax.swing.JButton();
        howToPlayButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        highScoreButton = new javax.swing.JButton();
        aboutTheGameButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(null);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit/exit.png"))); // NOI18N
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setFocusPainted(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(0, 0, 200, 70);

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sound/on.png"))); // NOI18N
        sound.setBorderPainted(false);
        sound.setContentAreaFilled(false);
        sound.setFocusPainted(false);
        sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundActionPerformed(evt);
            }
        });
        getContentPane().add(sound);
        sound.setBounds(1240, 0, 122, 128);

        howToPlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/how-to-play.png"))); // NOI18N
        howToPlayButton.setBorderPainted(false);
        howToPlayButton.setContentAreaFilled(false);
        howToPlayButton.setFocusPainted(false);
        howToPlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                howToPlayButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                howToPlayButtonMouseExited(evt);
            }
        });
        howToPlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(howToPlayButton);
        howToPlayButton.setBounds(550, 230, 270, 87);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/play.png"))); // NOI18N
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.setFocusPainted(false);
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playButtonMouseExited(evt);
            }
        });
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton);
        playButton.setBounds(552, 366, 270, 91);

        highScoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/high-scores.png"))); // NOI18N
        highScoreButton.setBorderPainted(false);
        highScoreButton.setContentAreaFilled(false);
        highScoreButton.setFocusPainted(false);
        highScoreButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                highScoreButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                highScoreButtonMouseExited(evt);
            }
        });
        highScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreButtonActionPerformed(evt);
            }
        });
        getContentPane().add(highScoreButton);
        highScoreButton.setBounds(552, 507, 270, 91);

        aboutTheGameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/about-the-game.png"))); // NOI18N
        aboutTheGameButton.setBorderPainted(false);
        aboutTheGameButton.setContentAreaFilled(false);
        aboutTheGameButton.setFocusPainted(false);
        aboutTheGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutTheGameButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutTheGameButtonMouseExited(evt);
            }
        });
        aboutTheGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutTheGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aboutTheGameButton);
        aboutTheGameButton.setBounds(0, 697, 180, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/background.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(!Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute.png"));
            sound.setIcon(image);
            Home.audioClip.stop();
            Home.mute = true;
        }
        else{
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/on.png"));
            sound.setIcon(image);
            Home.audioClip.loop(Clip.LOOP_CONTINUOUSLY);
            Home.audioClip.start();
            Home.mute = false;
        }
    }//GEN-LAST:event_soundActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        exit.setTitle("Memory Game");
        exit.setSize(600, 446);
        exit.setVisible(true);
        exit.setLocationRelativeTo(null);
        exit.setResizable(false);
        frame.setEnabled(false);
        Exit.from = "Main";
    }//GEN-LAST:event_exitButtonActionPerformed

    public static void setIt(){
        frame.setEnabled(true);
    }
    
    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/exit.png"));
        exitButton.setIcon(image);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/exit-clicked.png"));
        exitButton.setIcon(image);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void howToPlayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howToPlayButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Home/how-to-play-clicked.png"));
        howToPlayButton.setIcon(image);
    }//GEN-LAST:event_howToPlayButtonMouseEntered

    private void howToPlayButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howToPlayButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Home/how-to-play.png"));
        howToPlayButton.setIcon(image);
    }//GEN-LAST:event_howToPlayButtonMouseExited

    private void howToPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlayButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        frame.setVisible(false);
        Open.open = "how";
        Open.main(null);
    }//GEN-LAST:event_howToPlayButtonActionPerformed

    private void playButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Home/play-clicked.png"));
        playButton.setIcon(image);
    }//GEN-LAST:event_playButtonMouseEntered

    private void playButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Home/play.png"));
        playButton.setIcon(image);
    }//GEN-LAST:event_playButtonMouseExited

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        frame.setVisible(false);
        Play.main(null);
    }//GEN-LAST:event_playButtonActionPerformed

    private void highScoreButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highScoreButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Home/high-scores-clicked.png"));
        highScoreButton.setIcon(image);
    }//GEN-LAST:event_highScoreButtonMouseEntered

    private void highScoreButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highScoreButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Home/high-scores.png"));
        highScoreButton.setIcon(image);
    }//GEN-LAST:event_highScoreButtonMouseExited

    private void highScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        frame.setVisible(false);
        HighScore.main(null);
    }//GEN-LAST:event_highScoreButtonActionPerformed

    private void aboutTheGameButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTheGameButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Home/about-the-game-clicked.png"));
        aboutTheGameButton.setIcon(image);
    }//GEN-LAST:event_aboutTheGameButtonMouseEntered

    private void aboutTheGameButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTheGameButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Home/about-the-game.png"));
        aboutTheGameButton.setIcon(image);
    }//GEN-LAST:event_aboutTheGameButtonMouseExited

    private void aboutTheGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutTheGameButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        frame.setVisible(false);
        AboutTheGame.main(null);
    }//GEN-LAST:event_aboutTheGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    Thread.sleep(2100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    frame = new Home();
                    frame.setTitle("Memory Game");
                    frame.setSize(1366, 768);
                    frame.setLocationRelativeTo(null);
                    frame.setResizable(false);
                    frame.setVisible(true);
                    frame.setVisible(false);
                } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        Open.open = "";
        Open.main(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutTheGameButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton highScoreButton;
    private javax.swing.JButton howToPlayButton;
    private javax.swing.JButton playButton;
    public static javax.swing.JButton sound;
    // End of variables declaration//GEN-END:variables
}