package Exit;


import Home.Home;
import Play.Play;
import HighScore.HighScore;
import AboutTheGame.AboutTheGame;
import AboutTheGameMakers.AboutTheGameMakers;
import HowToPlay.HowToPlay;
import ScenarioProfessor.ScenarioProfessor;
import ScenarioYasser.ScenarioYasser;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class Exit extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static Exit frame = null;
    public static boolean wait = true;
    public static String from = "";
    /**
     * Creates new form Exit
     */
    public Exit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yes = new javax.swing.JButton();
        no = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        yes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit/yes.png"))); // NOI18N
        yes.setBorderPainted(false);
        yes.setContentAreaFilled(false);
        yes.setFocusPainted(false);
        yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yesMouseExited(evt);
            }
        });
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        getContentPane().add(yes);
        yes.setBounds(340, 230, 169, 168);

        no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit/no.png"))); // NOI18N
        no.setBorderPainted(false);
        no.setContentAreaFilled(false);
        no.setFocusPainted(false);
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noMouseExited(evt);
            }
        });
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no);
        no.setBounds(90, 230, 169, 168);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit/background.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        switch (from) {
            case "Main":
                Home.setIt();
                break;
            case "Play":
                Play.setIt();
                break;
            case "highScore":
                HighScore.setIt();
                break;
            case "AboutTheGame":
                AboutTheGame.setIt();
                break;
            case "AboutTheGame2":
                AboutTheGameMakers.setIt();
                break;
            case "HowToPlay":
                HowToPlay.setIt();
                break;
            case "Scenario":
                ScenarioProfessor.setIt();
                break;
            case "Scenario2":
                ScenarioYasser.setIt();
                break;
        }
        this.setVisible(false);
    }//GEN-LAST:event_noActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        System.exit(0);
    }//GEN-LAST:event_yesActionPerformed

    private void yesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/yes-clicked.png"));
        yes.setIcon(image);
    }//GEN-LAST:event_yesMouseEntered

    private void yesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/yes.png"));
        yes.setIcon(image);
    }//GEN-LAST:event_yesMouseExited

    private void noMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/no-clicked.png"));
        no.setIcon(image);
    }//GEN-LAST:event_noMouseEntered

    private void noMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/no.png"));
        no.setIcon(image);
    }//GEN-LAST:event_noMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frame = new Exit();
                frame.setTitle("Memory Game");
                frame.setSize(600, 466);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton no;
    private javax.swing.JButton yes;
    // End of variables declaration//GEN-END:variables
}
