package Play;

import Home.Home;
import Home.Open;
import Exit.Exit;
import Ready.Ready;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class Play extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Play
     */
    public static Play frame = null;
    private final Exit exit = new Exit();
    
    public Play() throws FileNotFoundException, IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        easy = new javax.swing.JButton();
        medium = new javax.swing.JButton();
        hard = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        sound = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back/back(1).png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(0, 675, 110, 100);

        easy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Play/easy.png"))); // NOI18N
        easy.setBorderPainted(false);
        easy.setContentAreaFilled(false);
        easy.setFocusPainted(false);
        easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                easyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                easyMouseExited(evt);
            }
        });
        easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyActionPerformed(evt);
            }
        });
        getContentPane().add(easy);
        easy.setBounds(780, 90, 158, 160);

        medium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Play/medium.png"))); // NOI18N
        medium.setBorderPainted(false);
        medium.setContentAreaFilled(false);
        medium.setFocusPainted(false);
        medium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mediumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mediumMouseExited(evt);
            }
        });
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });
        getContentPane().add(medium);
        medium.setBounds(780, 260, 158, 158);

        hard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Play/hard.png"))); // NOI18N
        hard.setBorderPainted(false);
        hard.setContentAreaFilled(false);
        hard.setFocusPainted(false);
        hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hardMouseExited(evt);
            }
        });
        hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardActionPerformed(evt);
            }
        });
        getContentPane().add(hard);
        hard.setBounds(780, 430, 158, 160);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit/exit.png"))); // NOI18N
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setFocusPainted(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(0, 0, 200, 70);

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sound/on.png"))); // NOI18N
        sound.setBorderPainted(false);
        sound.setContentAreaFilled(false);
        sound.setFocusPainted(false);
        sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundActionPerformed(evt);
            }
        });
        getContentPane().add(sound);
        sound.setBounds(1240, 0, 122, 128);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Play/bachground.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Back/back(1)-clicked.png"));
        back.setIcon(image);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Back/back(1).png"));
        back.setIcon(image);
    }//GEN-LAST:event_backMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute.png"));
            Home.sound.setIcon(image);
        }
        Home.frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void easyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Play/easy-clicked.png"));
        easy.setIcon(image);
    }//GEN-LAST:event_easyMouseEntered

    private void easyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Play/easy.png"));
        easy.setIcon(image);
    }//GEN-LAST:event_easyMouseExited

    private void mediumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Play/medium-clicked.png"));
        medium.setIcon(image);
    }//GEN-LAST:event_mediumMouseEntered

    private void mediumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Play/medium.png"));
        medium.setIcon(image);
    }//GEN-LAST:event_mediumMouseExited

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        Open.open = "0";
        Ready.open = "2";
        Open.main(null);
        frame.setVisible(false);
    }//GEN-LAST:event_mediumActionPerformed

    private void hardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Play/hard-clicked.png"));
        hard.setIcon(image);
    }//GEN-LAST:event_hardMouseEntered

    private void hardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Play/hard.png"));
        hard.setIcon(image);
    }//GEN-LAST:event_hardMouseExited

    private void hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        Ready.background.setIcon(new ImageIcon(getClass().getResource("/Ready/paused-bachground-hard.png")));
        Open.open = "0";
        Ready.open = "3";
        Open.main(null);
        frame.setVisible(false);
    }//GEN-LAST:event_hardActionPerformed

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/exit-clicked.png"));
        exitButton.setIcon(image);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Exit/exit.png"));
        exitButton.setIcon(image);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        exit.setTitle("Memory Game");
        exit.setSize(600, 446);
        exit.setVisible(true);
        exit.setLocationRelativeTo(null);
        exit.setResizable(false);
        this.setEnabled(false);
        Exit.from = "Play";
    }//GEN-LAST:event_exitButtonActionPerformed

    public static void setIt(){
        frame.setEnabled(true);
    }
    
    private void soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(!Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute.png"));
            sound.setIcon(image);
            Home.audioClip.stop();
            Home.mute = true;
        }
        else{
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/on.png"));
            sound.setIcon(image);
            Home.audioClip.loop(Clip.LOOP_CONTINUOUSLY);
            Home.audioClip.start();
            Home.mute = false;
        }
    }//GEN-LAST:event_soundActionPerformed

    private void easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        Open.open = "0";
        Ready.open = "1";
        Open.main(null);
        frame.setVisible(false);
    }//GEN-LAST:event_easyActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    frame = new Play();
                    frame.setVisible(true);
                    frame.setTitle("Memory Game");
                    frame.setSize(1366, 768);
                    frame.setLocationRelativeTo(null);
                    frame.setResizable(false);
                } catch (IOException ex) {
                    Logger.getLogger(Play.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(Home.mute){
                    ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute(1).png"));
                    sound.setIcon(image);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton easy;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hard;
    private javax.swing.JButton medium;
    private static javax.swing.JButton sound;
    // End of variables declaration//GEN-END:variables
}
