package HighScore;

import Home.Home;
import Exit.Exit;
import java.awt.Color;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class HighScore extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
        private final Exit exit = new Exit();
    public static HighScore frame = new HighScore();
    /**
     * Creates new form HighScore
     */
    public HighScore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sound = new javax.swing.JButton();
        easy = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        hard = new javax.swing.JButton();
        medium = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sound/on(1).png"))); // NOI18N
        sound.setBorderPainted(false);
        sound.setContentAreaFilled(false);
        sound.setFocusPainted(false);
        sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundActionPerformed(evt);
            }
        });
        getContentPane().add(sound);
        sound.setBounds(1266, 0, 100, 100);

        easy.setText("0");
        easy.setBorderPainted(false);
        easy.setContentAreaFilled(false);
        getContentPane().add(easy);
        easy.setBounds(220, 310, 270, 140);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExitTheGame/exit.png"))); // NOI18N
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setFocusPainted(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(3, 1, 100, 100);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back/back(1).png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(3, 676, 100, 90);

        hard.setText("0");
        hard.setBorderPainted(false);
        hard.setContentAreaFilled(false);
        getContentPane().add(hard);
        hard.setBounds(860, 300, 290, 160);

        medium.setText("0");
        medium.setBorderPainted(false);
        medium.setContentAreaFilled(false);
        getContentPane().add(medium);
        medium.setBounds(540, 310, 280, 140);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HighScore/background.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(!Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute(1).png"));
            sound.setIcon(image);
            Home.audioClip.stop();
            Home.mute = true;
        }
        else{
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/on(1).png"));
            sound.setIcon(image);
            Home.audioClip.loop(Clip.LOOP_CONTINUOUSLY);
            Home.audioClip.start();
            Home.mute = false;
        }
    }//GEN-LAST:event_soundActionPerformed

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/ExitTheGame/exit-clicked.png"));
        exitButton.setIcon(image);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/ExitTheGame/exit.png"));
        exitButton.setIcon(image);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        exit.setTitle("Memory Game");
        exit.setSize(600, 446);
        exit.setVisible(true);
        exit.setLocationRelativeTo(null);
        exit.setResizable(false);
        this.setEnabled(false);
        Exit.from = "highScore";
    }//GEN-LAST:event_exitButtonActionPerformed

    public static void setIt(){
        frame.setEnabled(true);
    }
    
    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Back/back(1)-clicked.png"));
        back.setIcon(image);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Back/back(1).png"));
        back.setIcon(image);
    }//GEN-LAST:event_backMouseExited

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute.png"));
            Home.sound.setIcon(image);
        }
        Home.frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            Scanner EasyScanner;
            Scanner MediumScanner;
            Scanner HardScanner;
            /* Create and display the form */
            
            EasyScanner = new Scanner(Home.scoreEasy);
            MediumScanner = new Scanner(Home.scoreMedium);
            HardScanner = new Scanner(Home.scoreHard);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    easy.setForeground(Color.BLUE);
                    Font font = new Font("SansSerif", Font.BOLD, 50);
                    easy.setFont(font);
                    easy.setText(EasyScanner.next());
                    medium.setForeground(Color.BLUE);
                    medium.setFont(font);
                    medium.setText(MediumScanner.next());
                    hard.setForeground(Color.BLUE);
                    hard.setFont(font);
                    hard.setText(HardScanner.next());
                    frame.setVisible(true);
                    frame.setTitle("Memory Game");
                    frame.setSize(1366, 768);
                    frame.setLocationRelativeTo(null);
                    frame.setResizable(false);
                    if(Home.mute){
                        ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute(1).png"));
                        sound.setIcon(image);
                    }
                }
            });
        } catch (FileNotFoundException ex) {
                Logger.getLogger(HighScore.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    public static javax.swing.JButton easy;
    private javax.swing.JButton exitButton;
    public static javax.swing.JButton hard;
    public static javax.swing.JButton medium;
    private static javax.swing.JButton sound;
    // End of variables declaration//GEN-END:variables
}
