package EasyLevel;

import ExitTheGame.ExitTheGame;
import Home.Home;
import Losing.Losing;
import MediumLevel.MediumLevel;
import Pause.Pause;
import Winning.Winning;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.net.URL;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class EasyLevel extends javax.swing.JFrame {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    public static EasyLevel frame = new EasyLevel();
    private final ExitTheGame back = new ExitTheGame();
    private final Pause pause = new Pause();
    public static URL[] photos;
    public static URL hidden;
    public static URL[] clocks;
    public static URL[] numbers;
    public static URL[] lastClocks;
    public static URL[] lastNumbers;
    public static int[] x;
    private boolean isOpen = false;
    private int noOpen = -1;
    private JButton whatOpen = null;
    private static ArrayList<Integer> indexs;
    private int count = 0;
    private static int score;
    private static PrintWriter output = null;
    private static Scanner scannerEasy = null;
    private static int scoreFile = 0;
    /**
     * Creates new form Level1
     */
    public EasyLevel(){
        x = new int[8];
        indexs = Create1(4);
        score = 99;
        EasyLevel.lastNumbers = new URL[]{getClass().getResource("/Timer/last ten sec/n0-danger.png"), getClass().getResource("/Timer/last ten sec/n1-danger.png"), getClass().getResource("/Timer/last ten sec/n2-danger.png"), getClass().getResource("/Timer/last ten sec/n3-danger.png"), getClass().getResource("/Timer/last ten sec/n4-danger.png"), getClass().getResource("/Timer/last ten sec/n5-danger.png"), getClass().getResource("/Timer/last ten sec/n6-danger.png"), getClass().getResource("/Timer/last ten sec/n7--danger.png"), getClass().getResource("/Timer/last ten sec/n8-danger.png"), getClass().getResource("/Timer/last ten sec/n9-danger.png")};
        EasyLevel.lastClocks = new URL[]{getClass().getResource("/Timer/last ten sec/1.png"), getClass().getResource("/Timer/last ten sec/2.png"), getClass().getResource("/Timer/last ten sec/3.png"), getClass().getResource("/Timer/last ten sec/4.png")};
        EasyLevel.numbers = new URL[]{getClass().getResource("/Timer/n0.png"), getClass().getResource("/Timer/n1.png"), getClass().getResource("/Timer/n2.png"), getClass().getResource("/Timer/n3.png"), getClass().getResource("/Timer/n4.png"), getClass().getResource("/Timer/n5.png"), getClass().getResource("/Timer/n6.png"), getClass().getResource("/Timer/n7.png"), getClass().getResource("/Timer/n8.png"), getClass().getResource("/Timer/n9.png")};
        EasyLevel.clocks = new URL[]{getClass().getResource("/Timer/1.png"), getClass().getResource("/Timer/2.png"), getClass().getResource("/Timer/3.png"), getClass().getResource("/Timer/4.png")};
        EasyLevel.hidden = getClass().getResource("/EasyLevel/hidden.png");
        EasyLevel.photos = new URL[]{getClass().getResource("/EasyLevel/1.png"), getClass().getResource("/EasyLevel/2.png"), getClass().getResource("/EasyLevel/3.png"), getClass().getResource("/EasyLevel/4.png")};
        initComponents();
    }
    
    public static ArrayList<Integer> Create1(int n){
        ArrayList<Integer> A  = new ArrayList<>();
        int k=1;
        for(int i=0;i<n*2;i++){
            if(i%2==0&&i!=0)
                k++;
            A.add(k);
        }
        
        ArrayList<Integer> b = new ArrayList<>();
        for(int i=0;i<2*n;i++){
            int o=A.size()-1;
            int a=(int) (Math.random()*o);
            b.add(A.get(a));
            A.remove(a);
        }
        return b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button2 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        sound = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        digit1 = new javax.swing.JButton();
        digit0 = new javax.swing.JButton();
        clock = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/hidden.png"))); // NOI18N
        Button2.setBorderPainted(false);
        Button2.setContentAreaFilled(false);
        Button2.setFocusPainted(false);
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        getContentPane().add(Button2);
        Button2.setBounds(300, 50, 240, 240);

        Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/hidden.png"))); // NOI18N
        Button1.setBorderPainted(false);
        Button1.setContentAreaFilled(false);
        Button1.setFocusPainted(false);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1);
        Button1.setBounds(80, 50, 240, 240);

        Button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/hidden.png"))); // NOI18N
        Button4.setBorderPainted(false);
        Button4.setContentAreaFilled(false);
        Button4.setFocusPainted(false);
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        getContentPane().add(Button4);
        Button4.setBounds(300, 270, 240, 240);

        Button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/hidden.png"))); // NOI18N
        Button5.setBorderPainted(false);
        Button5.setContentAreaFilled(false);
        Button5.setFocusPainted(false);
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        getContentPane().add(Button5);
        Button5.setBounds(520, 270, 240, 240);

        Button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/hidden.png"))); // NOI18N
        Button8.setBorderPainted(false);
        Button8.setContentAreaFilled(false);
        Button8.setFocusPainted(false);
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        getContentPane().add(Button8);
        Button8.setBounds(520, 490, 240, 240);

        Button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/hidden.png"))); // NOI18N
        Button3.setBorderPainted(false);
        Button3.setContentAreaFilled(false);
        Button3.setFocusPainted(false);
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        getContentPane().add(Button3);
        Button3.setBounds(80, 270, 240, 240);

        Button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/hidden.png"))); // NOI18N
        Button7.setBorderPainted(false);
        Button7.setContentAreaFilled(false);
        Button7.setFocusPainted(false);
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        getContentPane().add(Button7);
        Button7.setBounds(300, 490, 240, 240);

        Button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/hidden.png"))); // NOI18N
        Button6.setBorderPainted(false);
        Button6.setContentAreaFilled(false);
        Button6.setFocusPainted(false);
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        getContentPane().add(Button6);
        Button6.setBounds(80, 490, 240, 240);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExitTheGame/exit.png"))); // NOI18N
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setFocusPainted(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(0, 0, 100, 100);

        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sound/on(1).png"))); // NOI18N
        sound.setBorderPainted(false);
        sound.setContentAreaFilled(false);
        sound.setFocusPainted(false);
        sound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundActionPerformed(evt);
            }
        });
        getContentPane().add(sound);
        sound.setBounds(1262, 0, 100, 100);

        pauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pause/pause.png"))); // NOI18N
        pauseButton.setBorderPainted(false);
        pauseButton.setContentAreaFilled(false);
        pauseButton.setFocusPainted(false);
        pauseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pauseButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pauseButtonMouseExited(evt);
            }
        });
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pauseButton);
        pauseButton.setBounds(1220, 650, 80, 80);

        digit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Timer/n0.png"))); // NOI18N
        digit1.setBorderPainted(false);
        digit1.setFocusPainted(false);
        getContentPane().add(digit1);
        digit1.setBounds(1020, 70, 102, 170);

        digit0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Timer/n0.png"))); // NOI18N
        digit0.setBorderPainted(false);
        digit0.setFocusPainted(false);
        getContentPane().add(digit0);
        digit0.setBounds(1120, 70, 102, 170);

        clock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Timer/1.png"))); // NOI18N
        clock.setBorderPainted(false);
        clock.setContentAreaFilled(false);
        clock.setDefaultCapable(false);
        clock.setFocusPainted(false);
        getContentPane().add(clock);
        clock.setBounds(860, 140, 150, 220);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EasyLevel/bachground.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/ExitTheGame/exit-clicked.png"));
        backButton.setIcon(image);
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/ExitTheGame/exit.png"));
        backButton.setIcon(image);
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        back.setTitle("Memory Game");
        back.setSize(600, 446);
        back.setVisible(true);
        back.setLocationRelativeTo(null);
        back.setResizable(false);
        frame.setEnabled(false);
        ExitTheGame.from = "Level1";
    }//GEN-LAST:event_backButtonActionPerformed

    public static void setIt(){
        frame.setEnabled(true);
    }
    
    private void soundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(!Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute(1).png"));
            sound.setIcon(image);
            Home.audioClip.stop();
            Home.mute = true;
        }
        else{
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/on(1).png"));
            sound.setIcon(image);
            Home.audioClip.loop(Clip.LOOP_CONTINUOUSLY);
            Home.audioClip.start();
            Home.mute = false;
        }
    }//GEN-LAST:event_soundActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        pause.setTitle("Memory Game");
        pause.setSize(1366, 768);
        pause.setVisible(true);
        pause.setLocationRelativeTo(null);
        pause.setResizable(false);
        frame.setEnabled(false);
        Pause.from = "Level1";
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void pauseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/Pause/pause-clicked.png"));
        pauseButton.setIcon(image);
    }//GEN-LAST:event_pauseButtonMouseEntered

    private void pauseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/Pause/pause.png"));
        pauseButton.setIcon(image);
    }//GEN-LAST:event_pauseButtonMouseExited

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        if(whatOpen != Button1){
            Button1.setIcon(new ImageIcon(photos[x[0]]));
            frame.update(getGraphics());
            delay(500);
            if(isOpen){
                if(noOpen == x[0]){
                    Home.audioClip3.loop(1);
                    Home.audioClip3.start();
                    whatOpen.setVisible(false);
                    Button1.setVisible(false);
                    count += 2;
                    if(count == 8){
                        Home.audioClip2.loop(1);
                        Home.audioClip2.start();
                        Winning.from = "Level1";
                        Winning.score.setText(String.valueOf(score));
                        Winning.main(null);
                        frame.setVisible(false);
                        if((score) > scoreFile){
                            try {
                                output = new PrintWriter(Home.scoreEasy);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(EasyLevel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            output.print(score);
                            output.close();
                        }
                    }
                }
                else{
                    whatOpen.setIcon(new ImageIcon(hidden));
                    Button1.setIcon(new ImageIcon(hidden));
                }
                whatOpen = null;
                isOpen = false;
                noOpen = -1;
            }
            else{
                isOpen = true;
                noOpen = x[0];
                whatOpen = Button1;
            }
        }
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        if(whatOpen != Button2){
            Button2.setIcon(new ImageIcon(photos[x[1]]));
            frame.update(getGraphics());
            delay(500);
            if(isOpen){
                if(noOpen == x[1]){
                    Home.audioClip3.loop(1);
                    Home.audioClip3.start();
                    whatOpen.setVisible(false);
                    Button2.setVisible(false);
                    count += 2;
                    if(count == 8){
                       Home.audioClip2.loop(1);
                        Home.audioClip2.start();
                        Winning.from = "Level1";
                        Winning.score.setText(String.valueOf(score));
                        Winning.main(null);
                        frame.setVisible(false);
                        if((score) > scoreFile){
                            try {
                                output = new PrintWriter(Home.scoreEasy);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(EasyLevel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            output.print(score);
                            output.close();
                        }
                    }
                }
                else{
                    whatOpen.setIcon(new ImageIcon(hidden));
                    Button2.setIcon(new ImageIcon(hidden)); 
                }
                whatOpen = null;
                isOpen = false;
                noOpen = -1;
            }
            else{
                isOpen = true;
                noOpen = x[1];
                whatOpen = Button2;
            }
        }
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        if(whatOpen != Button3){
            Button3.setIcon(new ImageIcon(photos[x[2]]));
            frame.update(getGraphics());
            delay(500);
            if(isOpen){
                if(noOpen == x[2]){
                    Home.audioClip3.loop(1);
                    Home.audioClip3.start();
                    whatOpen.setVisible(false);
                    Button3.setVisible(false);
                    count += 2;
                    if(count == 8){
                        Home.audioClip2.loop(1);
                        Home.audioClip2.start();
                        Winning.from = "Level1";
                        Winning.score.setText(String.valueOf(score));
                        Winning.main(null);
                        frame.setVisible(false);
                        if((score) > scoreFile){
                            try {
                                output = new PrintWriter(Home.scoreEasy);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(EasyLevel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            output.print(score);
                            output.close();
                        }
                    }
                }
                else{
                    whatOpen.setIcon(new ImageIcon(hidden));
                    Button3.setIcon(new ImageIcon(hidden)); 
                }
                whatOpen = null;
                isOpen = false;
                noOpen = -1;
            }
            else{
                isOpen = true;
                noOpen = x[2];
                whatOpen = Button3;
            }
        }
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        if(whatOpen != Button4){
            Button4.setIcon(new ImageIcon(photos[x[3]]));
            frame.update(getGraphics());
            delay(500);
            if(isOpen){
                if(noOpen == x[3]){
                    Home.audioClip3.loop(1);
                    Home.audioClip3.start();
                    whatOpen.setVisible(false);
                    Button4.setVisible(false);
                    count += 2;
                    if(count == 8){
                        Home.audioClip2.loop(1);
                        Home.audioClip2.start();
                        Winning.from = "Level1";
                        Winning.score.setText(String.valueOf(score));
                        Winning.main(null);
                        frame.setVisible(false);
                        if((score) > scoreFile){
                            try {
                                output = new PrintWriter(Home.scoreEasy);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(EasyLevel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            output.print(score);
                            output.close();
                        }
                    }
                }
                else{
                    whatOpen.setIcon(new ImageIcon(hidden));
                    Button4.setIcon(new ImageIcon(hidden)); 
                }
                whatOpen = null;
                isOpen = false;
                noOpen = -1;
            }
            else{
                isOpen = true;
                noOpen = x[3];
                whatOpen = Button4;
            }
        }
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        if(whatOpen != Button5){
            Button5.setIcon(new ImageIcon(photos[x[4]]));
            frame.update(getGraphics());
            delay(500);
            if(isOpen){
                if(noOpen == x[4]){
                    Home.audioClip3.loop(1);
                    Home.audioClip3.start();
                    whatOpen.setVisible(false);
                    Button5.setVisible(false);
                    count += 2;
                    if(count == 8){
                        Home.audioClip2.loop(1);
                        Home.audioClip2.start();
                        Winning.from = "Level1";
                        Winning.score.setText(String.valueOf(score));
                        Winning.main(null);
                        frame.setVisible(false);
                        if((score) > scoreFile){
                            try {
                                output = new PrintWriter(Home.scoreEasy);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(EasyLevel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            output.print(score);
                            output.close();
                        }
                    }
                }
                else{
                    whatOpen.setIcon(new ImageIcon(hidden));
                    Button5.setIcon(new ImageIcon(hidden)); 
                }
                whatOpen = null;
                isOpen = false;
                noOpen = -1;
            }
            else{
                isOpen = true;
                noOpen = x[4];
                whatOpen = Button5;
            }
        }
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        if(whatOpen != Button6){
            Button6.setIcon(new ImageIcon(photos[x[5]]));
            frame.update(getGraphics());
            delay(500);
            if(isOpen){
                if(noOpen == x[5]){
                    Home.audioClip3.loop(1);
                    Home.audioClip3.start();
                    whatOpen.setVisible(false);
                    Button6.setVisible(false);
                    count += 2;
                    if(count == 8){
                        Home.audioClip2.loop(1);
                        Home.audioClip2.start();
                        Winning.from = "Level1";
                        Winning.score.setText(String.valueOf(score));
                        Winning.main(null);
                        frame.setVisible(false);
                        if((score) > scoreFile){
                            try {
                                output = new PrintWriter(Home.scoreEasy);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(EasyLevel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            output.print(score);
                            output.close();
                        }
                    }
                }
                else{
                    whatOpen.setIcon(new ImageIcon(hidden));
                    Button6.setIcon(new ImageIcon(hidden)); 
                }
                whatOpen = null;
                isOpen = false;
                noOpen = -1;
            }
            else{
                isOpen = true;
                noOpen = x[5];
                whatOpen = Button6;
            }
        }
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        if(whatOpen != Button7){
            Button7.setIcon(new ImageIcon(photos[x[6]]));
            frame.update(getGraphics());
            delay(500);
            if(isOpen){
                if(noOpen == x[6]){
                    Home.audioClip3.loop(1);
                    Home.audioClip3.start();
                    whatOpen.setVisible(false);
                    Button7.setVisible(false);
                    count += 2;
                    if(count == 8){
                        Home.audioClip2.loop(1);
                        Home.audioClip2.start();
                        Winning.from = "Level1";
                        Winning.score.setText(String.valueOf(score));
                        Winning.main(null);
                        frame.setVisible(false);
                        if((score) > scoreFile){
                            try {
                                output = new PrintWriter(Home.scoreEasy);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(EasyLevel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            output.print(score);
                            output.close();
                        }
                    }
                }
                else{
                    whatOpen.setIcon(new ImageIcon(hidden));
                    Button7.setIcon(new ImageIcon(hidden)); 
                }
                whatOpen = null;
                isOpen = false;
                noOpen = -1;
            }
            else{
                isOpen = true;
                noOpen = x[6];
                whatOpen = Button7;
            }
        }
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        if(whatOpen != Button8){
            Button8.setIcon(new ImageIcon(photos[x[7]]));
            frame.update(getGraphics());
            delay(500);
            if(isOpen){
                if(noOpen == x[7]){
                    Home.audioClip3.loop(1);
                    Home.audioClip3.start();
                    whatOpen.setVisible(false);
                    Button8.setVisible(false);
                    count += 2;
                    if(count == 8){
                        Home.audioClip2.loop(1);
                        Home.audioClip2.start();
                        Winning.from = "Level1";
                        Winning.score.setText(String.valueOf(score));
                        Winning.main(null);
                        frame.setVisible(false);
                        if((score) > scoreFile){
                            try {
                                output = new PrintWriter(Home.scoreEasy);
                            } catch (FileNotFoundException ex) {
                                Logger.getLogger(EasyLevel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            output.print(score);
                            output.close();
                        }
                    }
                }
                else{
                    whatOpen.setIcon(new ImageIcon(hidden));
                    Button8.setIcon(new ImageIcon(hidden)); 
                }
                whatOpen = null;
                isOpen = false;
                noOpen = -1;
            }
            else{
                isOpen = true;
                noOpen = x[7];
                whatOpen = Button8;
            }
        }
    }//GEN-LAST:event_Button8ActionPerformed

    public static void delay(double time){
        double end = System.currentTimeMillis() + time;
        while(System.currentTimeMillis() < end){
        }
    }
    
    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException {
        scannerEasy = new Scanner(Home.scoreEasy);
        scoreFile = scannerEasy.nextInt();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frame.setTitle("Memory Game");
                frame.setSize(1366, 768);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                frame.setVisible(true);
                Button1.setIcon(new ImageIcon(photos[(int)indexs.get(0)-1]));
                x[0] = (int)indexs.get(0)-1;
                Button2.setIcon(new ImageIcon(photos[(int)indexs.get(1)-1]));
                x[1] = (int)indexs.get(1)-1;
                Button3.setIcon(new ImageIcon(photos[(int)indexs.get(2)-1]));
                x[2] = (int)indexs.get(2)-1;
                Button4.setIcon(new ImageIcon(photos[(int)indexs.get(3)-1]));
                x[3] = (int)indexs.get(3)-1;
                Button5.setIcon(new ImageIcon(photos[(int)indexs.get(4)-1]));
                x[4] = (int)indexs.get(4)-1;
                Button6.setIcon(new ImageIcon(photos[(int)indexs.get(5)-1]));
                x[5] = (int)indexs.get(5)-1;
                Button7.setIcon(new ImageIcon(photos[(int)indexs.get(6)-1]));
                x[6] = (int)indexs.get(6)-1;
                Button8.setIcon(new ImageIcon(photos[(int)indexs.get(7)-1]));
                x[7] = (int)indexs.get(7)-1;
                if(Home.mute){
                    ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute(1).png"));
                    sound.setIcon(image);
                }
            }
        });
        delay(1500);
        Button1.setIcon(new ImageIcon(hidden));
        Button2.setIcon(new ImageIcon(hidden));
        Button3.setIcon(new ImageIcon(hidden));
        Button4.setIcon(new ImageIcon(hidden));
        Button5.setIcon(new ImageIcon(hidden));
        Button6.setIcon(new ImageIcon(hidden));
        Button7.setIcon(new ImageIcon(hidden));
        Button8.setIcon(new ImageIcon(hidden));
        for(int i=9, j=9 ; j>=0 ; ){
            if(frame.isActive())
                i--;
            if(i < 0)
                break;
            if(j==0 && frame.isActive()){
                digit0.setIcon(new ImageIcon(lastNumbers[i]));
                digit1.setIcon(new ImageIcon(lastNumbers[j]));
                score--;
                for(int k=0 ; k<4 ; k++){
                    delay(250);
                    clock.setIcon(new ImageIcon(lastClocks[k]));
                }
            }
            else if(frame.isActive()){
                digit0.setIcon(new ImageIcon(numbers[i]));
                digit1.setIcon(new ImageIcon(numbers[j]));
                score--;
                for(int k=0 ; k<4 ; k++){
                    delay(250);
                    clock.setIcon(new ImageIcon(clocks[k]));
                }
                if(i == 0){
                    i = 10;
                    j--;
                }
            }
        }
        Losing.from = "Level1";
        Losing.main(null);
        Home.audioClip4.loop(1);
        Home.audioClip4.start();
        frame.setVisible(false);
        frame = new EasyLevel();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Button1;
    public static javax.swing.JButton Button2;
    public static javax.swing.JButton Button3;
    public static javax.swing.JButton Button4;
    public static javax.swing.JButton Button5;
    public static javax.swing.JButton Button6;
    public static javax.swing.JButton Button7;
    public static javax.swing.JButton Button8;
    private static javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    public static javax.swing.JButton clock;
    public static javax.swing.JButton digit0;
    public static javax.swing.JButton digit1;
    private javax.swing.JButton pauseButton;
    private static javax.swing.JButton sound;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(EasyLevel.class.getName());
}
