package ExitTheGame;

import Home.Home;
import EasyLevel.EasyLevel;
import MediumLevel.MediumLevel;
import HardLevel.HardLevel;
import Home.Open;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class ExitTheGame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static ExitTheGame frame = new ExitTheGame();
    public static boolean wait = true;
    public static String from = "";
    /**
     * Creates new form Exit
     */
    public ExitTheGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yes = new javax.swing.JButton();
        no = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        yes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExitTheGame/yes.png"))); // NOI18N
        yes.setBorderPainted(false);
        yes.setContentAreaFilled(false);
        yes.setFocusPainted(false);
        yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yesMouseExited(evt);
            }
        });
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        getContentPane().add(yes);
        yes.setBounds(340, 230, 169, 168);

        no.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExitTheGame/no.png"))); // NOI18N
        no.setBorderPainted(false);
        no.setContentAreaFilled(false);
        no.setFocusPainted(false);
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noMouseExited(evt);
            }
        });
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no);
        no.setBounds(90, 230, 169, 168);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ExitTheGame/background.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        switch (from) {
            case "Level1":
                EasyLevel.setIt();
                break;
            case "Level2":
                MediumLevel.setIt();
                break;
            case "Level3":
                HardLevel.setIt();
                break;
        }
        this.setVisible(false);
    }//GEN-LAST:event_noActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        Home.audioClip1.loop(1);
        Home.audioClip1.start();
        if(Home.mute){
            ImageIcon image = new ImageIcon(getClass().getResource("/Sound/mute.png"));
            Home.sound.setIcon(image);
        }
        Home.frame.setVisible(true);
        this.setVisible(false);
        switch (from) {
            case "Level1":
                EasyLevel.frame.setVisible(false);
                break;
            case "Level2":
                MediumLevel.frame.setVisible(false);
                break;
            case "Level3":
                HardLevel.frame.setVisible(false);
                break;
        }
        Open.t1.stop();
    }//GEN-LAST:event_yesActionPerformed

    private void yesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/ExitTheGame/yes-clicked.png"));
        yes.setIcon(image);
    }//GEN-LAST:event_yesMouseEntered

    private void yesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/ExitTheGame/yes.png"));
        yes.setIcon(image);
    }//GEN-LAST:event_yesMouseExited

    private void noMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseEntered
        ImageIcon image = new ImageIcon(getClass().getResource("/ExitTheGame/no-clicked.png"));
        no.setIcon(image);
    }//GEN-LAST:event_noMouseEntered

    private void noMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseExited
        ImageIcon image = new ImageIcon(getClass().getResource("/ExitTheGame/no.png"));
        no.setIcon(image);
    }//GEN-LAST:event_noMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frame.setTitle("Memory Game");
                frame.setSize(600, 466);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton no;
    private javax.swing.JButton yes;
    // End of variables declaration//GEN-END:variables
}
