package Ready;


import Home.Open;
import java.net.URL;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmed
 */
public class Ready extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static Ready frame = new Ready();
    public static String open = "";
    private static URL[] counter;
    /**
     * Creates new form Pause
     */
    public Ready() {
        Ready.counter = new URL[]{getClass().getResource("/Ready/3.png"), getClass().getResource("/Ready/2.png"), getClass().getResource("/Ready/1.png"), getClass().getResource("/Ready/GO.png")};
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ready/3.png"))); // NOI18N
        label.setBorderPainted(false);
        label.setContentAreaFilled(false);
        label.setDefaultCapable(false);
        label.setFocusPainted(false);
        getContentPane().add(label);
        label.setBounds(220, 160, 520, 410);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ready/pause-bachground-easy&medium.png"))); // NOI18N
        background.setLabelFor(background);
        getContentPane().add(background);
        background.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static void time(double time){
        double end = System.currentTimeMillis() + time;
        while(System.currentTimeMillis() < end){
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frame.setTitle("Memory Game");
                frame.setSize(1366, 768);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
                frame.setVisible(true);
            }
        });
        time(250);
        for(int i=0 ; i<4 ; i++){
            label.setIcon(new ImageIcon(counter[i]));
            time(1000);
        }
        Open.open = Ready.open;
        switch (Open.open) {
            case "1":
                Open.main(null);
                break;
            case "2":
                Open.main(null);
                break;
            case "3":
                Open.main(null);
                break;
        }
        frame.setVisible(false);
        frame = new Ready();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel background;
    private static javax.swing.JButton label;
    // End of variables declaration//GEN-END:variables
}
